### ISSUE TITLE
Control flow in template!

### ISSUE THREAD

**Issue by lukechu10** [lukechu10/maple#18]
Implement control flow constructs (`if/else` and `for`) in `template!` macro.

**Comment by TheRawMeatball** [comment]
Hi, I just saw this project and I really like it. I tried to implement this by implementing nested effects, but it was much harder than expected and I couldn't get it to work. Do you have a better idea for how this can be accomplished?

**Comment by lukechu10** [comment]
> Hi, I just saw this project and I really like it. I tried to implement this by implementing nested effects, but it was much harder than expected and I couldn't get it to work. Do you have a better idea for how this can be accomplished?

First off, for the design, there are two potential ways to implement this. The most obvious one would be to introduce `if`/`else` and `for` constructs directly in the `template!` macro. The second one would be to use components for control flow (which is actually how solid-js does it: https://github.com/ryansolid/solid/blob/master/documentation/rendering.md).

I am personally in favor of the first option, that is, adding control flow directly to `template!` because it looks cleaner in the markup and it is more obvious that it is control flow, not components.

Arguments for favoring the second option, that is, using components, would include a simpler and smaller API. We would just need to build these components.

In any case, for the actual logic for rendering templates with control flow, it should just use `create_effect` to evaluate the condition and than render the appropriate template. For example, this could be what an if/else construct expands to with `template!`:

```rust
template! {
    @if condition() 
        p { # "true" }
    } else {
        p { # "false" }
    }
}

// expands to

{
    let node = /* unintialized_placeholder */;
    create_effect(move || {
        if condition() {
            let element = create_element("p");
            append(&element, text("true");
            element
        } else {
            let element = create_element("p");
            append(&element, text("false");
            element
        }
    });

    node.unwrap()
}
```
