### ISSUE TITLE
Component lifecycle

### ISSUE THREAD

**Issue by lukechu10** [lukechu10/maple#21]
**Is your feature request related to a problem? Please describe.**
Components should have some lifecycle hooks for `on_created` and `on_destroyed`.

**Describe the solution you'd like**
`on_created` is similar to `create_effect` except it only runs once.
`on_destoryed` is a bit more complicated. Currently, components are simply function calls. For `on_destroyed` to be implemented, the function call needs to be wrapped up in another `create_component` utility. This utility function will setup the lifecycle hooks for the code inside the component.

**Additional context**

**Questionnaire**
- [ ] I would like to implement this feature but I don't know where to start
- [x] I would like to implement this feature and I have a solution
- [ ] I don't have time to implement this / I don't want to implement this

**Comment by lukechu10** [comment]
> Hmm, would it be possible to put the destructor as the return value of an effect, kind of like react? Then, startup is an effect with no tracked gets, and it returns a closure as a destructor.

This PR is currently blocked by #29 
The problem with using effect as startup is that effects (currently) are run synchronously (although this might change in the future). Having the closure run once synchronously is not very interesting.

**Comment by TheRawMeatball** [comment]
> Having the closure run once synchronously is not very interesting.

Why? A single synchronous run should be enough to spawn and detach a future on the JS executor.

**Comment by lukechu10** [comment]
> Why? A single synchronous run should be enough to spawn and detach a future on the JS executor.

You can already do the same but simply not using an effect.
The `on_created` method will delay execution until rendering is complete.

**Comment by TheRawMeatball** [comment]
Hmm, perhaps `on_created` should be renamed `on_post_render`? A fetch request doesn't need to wait until rendering is done. Also, on_destroyed should probably be derived from the return value of `on_effect` or `on_created` to simplify the use case of cleanup functions.
