### ISSUE TITLE
Add more easing functions

### ISSUE THREAD

**Issue by lukechu10** [lukechu10/maple#88]
**Is your feature request related to a problem? Please describe.**
Maple ships with some easing functions out of the box for use with `Tweened`. They are in the `maple_core::easing` module. There are some easing functions that are missing, notably, `circular`, `sine`, `exponential`, `bounce` and perhaps some more.

**Describe the solution you'd like**
For all the different easing functions listed above, there should be `in`, `out` and `inout` variants.

**Additional context**
https://easings.net/ would be a good reference for the right mathematical functions for each ease function.

**Questionnaire**
- [ ] I would like to implement this feature but I don't know where to start
- [ ] I would like to implement this feature and I have a solution
- [ ] I don't have time to implement this / I don't want to implement this

**Comment by tmpr** [comment]
Hello! I would like to implement the `circular` and `exponential` functions! This is my first time ever contributing to some other repository, but I will give my best!

I do have a plan, yet not a solution.
